### ISSUE TITLE
Passing a map[string]someStruct through .Emit()/.Next()

### ISSUE THREAD

**Issue by rob-deutsch** [ipfs/go-ipfs-cmds#122]
Hi all, I'm trying to add a feature to IPFS, and a command is being run over HTTP.

I am passing a `theMap := map[string]someStruct{...}` through `.Next(*theMap)` and I have confirmed its being sent over HTTP as a JSON object.

However, in the client where I receive it with `.Next()` for some reason I'm only getting the first someStruct (not even the key) of the map.

Am I using Emit/Next correctly? Should this work?

**Comment by rob-deutsch** [comment]
Oh! Looking at another part of the codebase I noticed that the `Command` struct takes a `Type` and an `Encoder`. 

I think I've found the right investigation path: https://godoc.org/github.com/ipfs/go-ipfs-cmds#Command

**Comment by Stebalien** [comment]
That sounds like the correct diagnosis. Really, we should be complaining loudly (logging? panicing? if `Type` isn't specified and we try to `Emit` something *other* than an `io.Reader`.

**Comment by rob-deutsch** [comment]
Thanks for the confirmation.

In this case its totally my fault, though. I was hacking away at an existing piece of code that already had the type specified as `someStruct{}`. So I shouldn't be surprised at the results I was getting when I was emitting `map[string]someStruct{}` in certain situations.

I plan to modify my code now so that it always emits a `map[string]someStruct{}`. That is, if I want to emit a single `someStruct{}` I'll first wrap it in a map.

Does anything seem unreasonable about that?

**Comment by Stebalien** [comment]
That sounds reasonable.

**Comment by Stebalien** [comment]
(closing for tracking, feel free to continue discussing)

**Comment by rob-deutsch** [comment]
Thanks. Sorry that I didn't close it myself.

**Comment by Stebalien** [comment]
Np. I just like to close things *before* I forget about them for 3+ months :smile:.
