### ISSUE TITLE
Writing to Stderr from an Encoder

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs-cmds#133]
Is the current model that if a command needs to write to both stdout and stderr than PostRun should be used?

If so this seams like an overkill for example in `filestore verify` non-fatal errors may be printed to stderr.  By forcing this command to use a PostRun we lose the benefit of the Encoder.

CC @Stebalien @keks

**Comment by kevina** [comment]
This may be a duplicate of #115, or at least is closely related.

**Comment by Stebalien** [comment]
Yeah, it's basically the same issue. The current model is to just use a PostRun (ufnortunately).

**Comment by kevina** [comment]
@Stebalien thanks
