### ISSUE TITLE
codeclimate: "don't use underscores in Go names; var err_ should be err"

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmds#14]
There are cases where I need to handle two errors at once. In those cases I use the variable names `err` and `err_`. It's just like on IRC, if a name is aready taken you use `${name}_`, or in maths, e.g. `i` and `i'`.

I think this is a valid use of an underscore in a variable name, but I can't select WontFix in codeclimate since I'm not authorized.

@Kubuxu @whyrusleeping what do you think?

**Comment by Kubuxu** [comment]
I would suggest `err1`, `err2` or something like this. It conveys the intention more cleanly.

**Comment by keks** [comment]
Personally I think differently but I'll go with `err1` and `err2`.

**Comment by keks** [comment]
I went for `err` and `err2`.
