### ISSUE TITLE
Get rid of `Request.convertOptions`

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-cmds#183]
Currently, we:

1. Extract the options from the request parameters.
2. Stash them in the request options map.
3. Later, convert the options to the correct types, storing them back in the request.

This is bad practice. We should:

1. Extract the options from the request parameters.
2. Convert them.
3. Save them.

That is, we should never store temporary data in the place we expect to store the final data, then fix it up later.

**Comment by gargdeepak** [comment]
Can I please pick up this issue if no one else is working on it ?

**Comment by Stebalien** [comment]
That would be awesome! Fair warning, the code in this repo has been patched heavily and is a bit gnarly.

**Comment by gargdeepak** [comment]
Thanks @Stebalien !
I have pushed the fix here: https://github.com/gargdeepak/go-ipfs-cmds/tree/fix/cmds/req-refactor
I ran `go tests` and following the contribution guidelines.
Anything else I should do before sending out a PR ?

**Comment by Stebalien** [comment]
Go ahead and file a PR!

**Comment by gargdeepak** [comment]
needs review
