### ISSUE TITLE
Remove all dependencies to go-ipfs (except maybe legacy)

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmds#20]
This should be a general-purpose library.
Main issue is the Context struct, which contains and ipfs node and config. My current idea is to replace it with an additional argument `env` of type `interface{}` that can be passed to `cmd.Call()` and will be passed to `PreRun` and `PostRun`.

**Comment by keks** [comment]
However, definitely make legacy its own package, so this one can live without.

**Comment by Stebalien** [comment]
> Main issue is the Context struct

I'm worried about having type assertions all over the place but I can't really think of a better solution (other than to complain to the go devs about the lack of generics but that's not going to get us anywhere).

**Comment by keks** [comment]
The idea is to have the caller define a type, and functions that take an `interface{}` and cast to that type and work with it, something like
```go
// in go-ipfs/core/commands:

type Context {
  node *core.IpfsNode
  constructNode func() (*core.IpfsNode, error)
  // ...
}

func GetNode(env interface{}) (*core.IpfsNode, error) {
  ctx, ok := env.(Context)
  if !ok {
    return nil, fmt.Errorf("env is type %T, not %T", env, ctx)
  }

  if ctx.node == nil {
    n, err := ctx.constructNode()
    if err != nil {
      return err
    }

    ctx.node = n
  }

  return ctx.n
}
```
So when you are in a command and want to access the node, you just do
```go
cmd := &cmds.Command{
  Run: func(req cmds.Request, res cmds.ResponseEmitter, env interface{}) {
    n, err := cmds.GetNode(env)
    // // ...
```

Note that currently the context is defined in go-ipfs/commands and go-ipfs-cmds, but is moved to go-ipfs/core/commands, which is where the actual commands are defined. This is a much better fit, because the cmds library should be agnostic about the state that is required by the application at hand.
An exception of course is that the context contains the request log. The commands middleware will define an interface for type that allows adding values to and removing values from the request log. That way the core/commands.Context can just implement that interface and we can manage the log from within the commands library.
