### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmds#23]
Currently the tests don't run because we depend on go-ipfs and that depends on a lot of gx stuff.

Depends on #20.

Note: To run the tests you have to gxify the whole thing:

```
gx-go rewrite
go test ./...
gx-go rewrite --undo
```

**Comment by keks** [comment]
@Stebalien can I close this? Travis seems to be happy.

**Comment by Stebalien** [comment]
Ah, yeah, this was that circular dependency thing.
