### ISSUE TITLE
Http handler returns 200 OK on command panic

### ISSUE THREAD

**Issue by fabiobozzo** [ipfs/go-ipfs-cmds#249]
My team's fork of Kubo runs on a few custom interface implementations, notably the `Pinner`. 
Recently, we found a bug in one of them which caused a panic, in the context of a command.

We were surprised to find out that the http API returns 200 OK, in case of panic.  
In order to demonstrate that behaviour, I opened a PR, with a couple of new http handler tests. 
See: https://github.com/ipfs/go-ipfs-cmds/pull/250

**Comment by lidel** [comment]
Thank you, the remaining work will land in https://github.com/ipfs/kubo/issues/10398
