### ISSUE TITLE
Make Request pretty

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmds#3]
Especially the setters should go. A `Request` is created by someone and then passed on. They can make a struct that implement that interface, that is specific to the situation.

Also, maybe `Request` can even be a struct, like in `net/http`? I'm not sure that's a good idea, just thinking out loud...

**Comment by keks** [comment]
currently it is 

```go
type Request interface {
    Path() []string
    Option(name string) *cmdsutil.OptionValue
    Options() cmdsutil.OptMap
    SetOption(name string, val interface{})
    SetOptions(opts cmdsutil.OptMap) error
    Arguments() []string
    StringArguments() []string
    SetArguments([]string)
    Files() files.File
    SetFiles(files.File)
    Context() context.Context
    SetRootContext(context.Context) error
    InvocContext() *Context
    SetInvocContext(Context)
    Command() *Command
    Values() map[string]interface{}
    Stdin() io.Reader
    VarArgs(func(string) error) error

    ConvertOptions() error
}
```

Starting to think we actually want a struct.

**Comment by keks** [comment]
Issues with Request:
- Currently it's an interface with getters and setters for everything. That doesn't make sense at all.
- Remove `Option()`, as we are usually not interested in the option specification when handling commands. And if we are, we can access them using `Commands`.
- `Values` is ugly (because it passes values that you can't see in function signatures) and superfluous as we can just use the context for this use case. Also it's only used in one place (the add command)
- `InvocContext` makes us depend on go-ipfs, so that should be removed as well. I propose that instead the user can pass an argument to `cmd.Call` which is passed on to `cmd.Run`. Maybe call it environment?
- I'm not sure about `VarArgs`. I think it's best to parse all arguments at Request creation time (e.g. at parse time), which would also remvoe the need for `ConvertOptions`.

Based on these thoughts I suggest the new `Request` type to be
```go
type Request struct {
	Context context.Context
	Command *Command

	Path      []string
	Arguments []string
	Options   cmdkit.OptMap

	Body  io.Reader
	Files files.File
}
```

**Comment by Kubuxu** [comment]
@keks VarArgs can be streamed in, not all of them have to exist at the point when command is "called" we use it in many places where waiting for all arguments might cause us to run out of memory.

**Comment by keks** [comment]
@Kubuxu thanks for the heads up, I'll take that into account. My current idea is to make something that behaves similar to e.g. `bufio.Scanner`:
```go
func handler(req *Request, re Responseemitter) {
	args := req.BodyArgs()
	for args.Next() {
		arg := args.Arg()
		// do stuff with argument
	}
	// ...
}
```

Looking at this, I could really just expose the Scanner that is currently used in VarArgs...

**Comment by Kubuxu** [comment]
Ahh,  I might be thinking about `Files().NextFile()`.

**Comment by keks** [comment]
Looking into this again, [sourcegraph] tells me that noone is using `Stdin`. Also, it *always* returns `os.Stdin`, so when the server receives a request, it will contain the server's stdin. Not very useful. So I'll kick that one as well, but think about a good, standard way to set stdin as a file.
Currently it sets it with name `/dev/stdin` (`os.Stdin.Name()`, that is), and the vararg parser just calls `req.Files.Nextfile()` and seems to *hope* that the first file it gets is the client's stdin. I'll try to figure out a good way to make sure that stdin is only used once (either as container for vararg or as a file) and that vararg iteration uses the right `files.File`.

**Comment by Kubuxu** [comment]
90% of commands are using the InvocContext from Request to get the node instance and some modules from it so we will need some easy to use helper function for that.

**Comment by keks** [comment]
It will not be part of the request anymore. Instead, an `interface{}` value can be passed to `cmd.Call`, which will be forwarded to `Run`. That way go-ipfs-cmds won't need to depend on ipfs anymore, making it possible to use for other projects.

To that end I'll also try to move the legacy layer to a subpackage, but I'm not sure yet if that'll work out.

**Comment by Kubuxu** [comment]
Yes, that is why helper function, that would do type casing, checks and so on because it is used by every command.

**Comment by keks** [comment]
I think we can safely use an unchecked type assertian to a well-known type that will look very similar to the old `cmds.Context`:
```go
func Run(req *cmds.Request, re cmds.ResponseEmitter, env interface{}) {
	ipfsEnv := env.(somePkg.IpfsEnv)
	// ...
}
```

**Comment by Kubuxu** [comment]
Yes but 
```go
func Run(req *cmds.Request, re cmds.ResponseEmitter, env interface{}) {
	ipfsNode := GetNode(env)
	// ...
}
```
 - looks better
 - allows for simpler future changes (what if env's meaning changes in future)
 - doesn't require you to import node's package in every command file and remember those paths and types

**Comment by keks** [comment]
Okay, I like that. One comment though:

> doesn't require you to import node's package in every command file and remember those paths and types

You wouldn't need to import the node's package anyway, just the one where IpfsEnv is defined. And with your construction it's the same, except it would be
```go
n, err := somePkg.GetNode(env)
```
instead of
```
ipfsEnv := env.(somePkg.IpfsEnv)
n, err := ipfsEnv.ConstructNode()
```

But yeah, I especially dig
>allows for simpler future changes (what if env's meaning changes in future)

**Comment by keks** [comment]
I still need to find a good place for `IpfsEnv` though. options I'm considering are (a) `go-ipfs/commands` and `go-ipfs-cmds/ipfs`.

**Comment by Kubuxu** [comment]
If you don't want to depend on go-ipfs it would need to be in `go-ipfs/commands` or go-ipfs/core/commands`.

**Comment by keks** [comment]
`go-ipfs-cmds` wouldn't need to depend on `go-ipfs-cmds/ipfs`, but I agree that `go-ipfs/(core/)?commands` is a better choice.
