### ISSUE TITLE
Wrap results in something indicating the type of the result

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-cmds#31]
That is, either:

```
{
    "Type": "error",
    "Code": 0,
    "Message": "my message"
}
```

Or:

```
{
    "Type": "value",
    "Value": { /* ... */ }
}
```

Currently, one can break the API as follows:

```sh
> ipfs dag put <<<'{"Message": "the api is broken", "Code": 0, "Type": "error"}'
zdpuAxiFRrxtmMmFRZx145LufQsKTw8is1ZgfTQX4vgzgb8DB

> ipfs dag get zdpuAxiFRrxtmMmFRZx145LufQsKTw8is1ZgfTQX4vgzgb8DB
Error: the api is broken
```

**Comment by Stebalien** [comment]
Note: we may end up just replacing this entire system before we get to this.

**Comment by keks** [comment]
>Note: we may end up just replacing this entire system before we get to this.

This. Changing the way we send values over the wire breaks backwards-compatibility, so let's just design a sane protocol from ground up. See #37.
