### ISSUE TITLE
Add minimial Makefile, use standard test script

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs-cmds#35]
For libp2p projects that don't have a Makefile I have been using this minimal one:
```
gx:
	go get github.com/whyrusleeping/gx
	go get github.com/whyrusleeping/gx-go

deps: gx
	gx --verbose install --global
	gx-go rewrite

publish:
	gx-go rewrite --undo

```

I have also converted them to use this standard test script: https://github.com/ipfs/ci-helpers/blob/master/travis-ci/run-standard-tests.sh

Should I create a p.r. for this?

**Comment by Stebalien** [comment]
SGTM.

**Comment by keks** [comment]
Yup sound good!

**Comment by kevina** [comment]
This is already done in #49.  The only thing I noticed was that the change added the `-race` to the tests and wonder if it was intentional or not.

**Comment by Stebalien** [comment]
Probably. It's good to have anyways.

Thanks for noticing this.
