### ISSUE TITLE
Rare error race

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-cmds#47]
When running `ipfs refs bad-path`, I'll ocationally see the following panic:

```
18:48:04.074 ERROR  cmds/http: a panic has occurred in the commands handler! handler.go:125
18:48:04.074 ERROR  cmds/http: connection already closed / custom - http.respem - TODO handler.go:126
18:48:04.074 ERROR  cmds/http: stack trace:
goroutine 351 [running]:
runtime/debug.Stack(0xc42015f280, 0xc42067a1f0, 0x1)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http.internalHandler.ServeHTTP.func1()
	/home/steb/projects/go/src/gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http/handler.go:127 +0x130
panic(0x12d0680, 0xc42067a090)
	/usr/lib/go/src/runtime/panic.go:491 +0x283
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http.(*responseEmitter).SetError(0xc420278e10, 0x12d0680, 0xc42004b960, 0x0)
	/home/steb/projects/go/src/gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http/responseemitter.go:159 +0x228
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds.(*fakeResponse).SetError(0xc4201e3040, 0x1cb8260, 0xc42004b960, 0x0)
	/home/steb/projects/go/src/gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/legacy.go:190 +0xa6
github.com/ipfs/go-ipfs/core/commands.glob..func114(0x1cce6a0, 0xc42065ff00, 0x1ccd700, 0xc4201e3040)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/commands/refs.go:112 +0x3be
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds.NewCommand.func1(0x1cce5e0, 0xc420326480, 0x6bc35a6cbf60, 0xc420278e10)
	/home/steb/projects/go/src/gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/legacy.go:404 +0x197
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds.(*Command).Call(0x1d9c0a0, 0x1cce5e0, 0xc420326480, 0x6bc35a6cbf60, 0xc420278e10, 0x0, 0x0)
	/home/steb/projects/go/src/gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/command.go:123 +0x1de
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http.internalHandler.ServeHTTP(0x0, 0xc42001c08a, 0x67, 0xc4205386f0, 0xc4201b6480, 0x15770f0, 0xc4201a8700, 0xc4203544f0, 0x1d9c0a0, 0xc420538690, ...)
	/home/steb/projects/go/src/gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http/handler.go:194 +0xa0d
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http.(*internalHandler).ServeHTTP(0xc4201e4aa0, 0x1cc2ae0, 0xc42000e720, 0xc420345e00)
	<autogenerated>:1 +0x72
gx/ipfs/QmPG2kW5t27LuHgHnvhUwbHCNHAt2eUcb4gPHqofrESUdB/cors.(*Cors).Handler.func1(0x1cc2ae0, 0xc42000e720, 0xc420345e00)
	/home/steb/projects/go/src/gx/ipfs/QmPG2kW5t27LuHgHnvhUwbHCNHAt2eUcb4gPHqofrESUdB/cors/cors.go:188 +0x108
net/http.HandlerFunc.ServeHTTP(0xc420528420, 0x1cc2ae0, 0xc42000e720, 0xc420345e00)
	/usr/lib/go/src/net/http/server.go:1918 +0x44
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http.Handler.ServeHTTP(0x0, 0xc42001c08a, 0x67, 0xc4205386f0, 0xc4201b6480, 0x15770f0, 0x0, 0xc4203544f0, 0x1d9c0a0, 0xc420538690, ...)
	/home/steb/projects/go/src/gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http/handler.go:117 +0x5e
gx/ipfs/QmP9vZfc5WSjfGTXmwX2EcicMFzmZ6fXn7HTdKYat6ccmH/go-ipfs-cmds/http.(*Handler).ServeHTTP(0xc42050a540, 0x1cc2ae0, 0xc42000e720, 0xc420345e00)
	<autogenerated>:1 +0x78
net/http.(*ServeMux).ServeHTTP(0xc42035dce0, 0x1cc2ae0, 0xc42000e720, 0xc420345e00)
	/usr/lib/go/src/net/http/server.go:2254 +0x130
net/http.(Handler).ServeHTTP-fm(0x1cc2ae0, 0xc42000e720, 0xc420345e00)
	/usr/lib/go/src/net/http/h2_bundle.go:5462 +0x4d
gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0x1cc4160, 0xc42074c8c0, 0xc420345e00)
	/home/steb/projects/go/src/gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus/http.go:287 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc4201e4a50, 0x1cc4160, 0xc42074c8c0, 0xc420345e00)
	/usr/lib/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42035dcb0, 0x1cc4160, 0xc42074c8c0, 0xc420345e00)
	/usr/lib/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc42032ea90, 0x1cc4160, 0xc42074c8c0, 0xc420345e00)
	/usr/lib/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42019b040, 0x1cc4fe0, 0xc4206901c0)
	/usr/lib/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2720 +0x288
 handler.go:127
```

While I usually can't reproduce this easily, it reproduces readily when running the `./t0110-gateway.sh` on commit cccd03e875ea961e96b225a910ae1f55d0eb83be (look at the `trash directory.t0110-gateway.sh/daemon_err` file).

**Comment by keks** [comment]
Hmm, the commit you reference is quite old and before we merged some changes to the legacy layer. Another observation: I think the error message regarding "connection already closed" is not correct. `re.w` is only set to `nil` when a HEAD request is made, which I believe go client never does. So instead I guess the value must be nil when it is passed to `NewResponseEmitter`, which is also weird.

**Comment by Stebalien** [comment]
> Hmm, the commit you reference is quite old and before we merged some changes to the legacy layer.

That commit is quite new. It's currently the third commit on master.

> I think the error message regarding "connection already closed" is not correct. re.w is only set to nil when a HEAD request is made, which I believe go client never does.

Ah. Sorry for misleading you, that would explain my difficulty in reproducing this error. The test case in question calls `HEAD` (using curl).

**Comment by keks** [comment]
Digging through this. The panic happend because Emit first checked whether `re.w == nil` (and error out) and only later would have returned nil when it checked that it is working on a HEAD request (where `re.w == nil` is expected). I now first check for whether it's a HEAD request.

However, the t0110 still doesn't pass. What I just realized is that the test calls `refs/local`, but the test fails in the handler for `refs`. Looks like it might be an issue with parsing the request.

**Comment by keks** [comment]
Yup, that's it. I built a unit test case in http/parse_test.go that reproduces this. Pushed it to branch `fix/http-parse` (which sits on top of `fix/head-requests`)

**Comment by keks** [comment]
Actually it seems like that is somewhat documented behaviour https://github.com/ipfs/go-ipfs-cmds/blob/master/http/parse.go#L46:L47. Which leaves me wondering why this didn't break the tests before (or why you would introduce this "feature" in the first place)

**Comment by keks** [comment]
Just found your commit fixing the sharness test - looks like I didn't tell you anything new. Anyway, I fixed printing the wrong error message in #48. Let's see what whyrusleeping says, maybe we can change the behaviour of the http API to not treat the last path element as an argument.

**Comment by Stebalien** [comment]
> Let's see what whyrusleeping says, maybe we can change the behaviour of the http API to not treat the last path element as an argument.

Unlikely... A lot of tools rely on that feature.

**Comment by Stebalien** [comment]
Likely fixed long ago.
