### ISSUE TITLE
Emit returning errors

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs-cmds#62]
I think it provides a pretty poor UX to have Emit return errors. It complicates the calling code a bit (what do we even do with the errors? we cant use SetError). Lets discuss how to address this.

**Comment by Stebalien** [comment]
Proposal: Entirely separate errors and values.

1. Make `SetError` set the *final* error (and close the request).
2. Use `Emit(err)` to send "informational" errors to the user.

This would also solve #31 as, in the HTTP case, RCP-level errors would be sent via trailer headers only (never inline as content).

**Comment by dignifiedquire** [comment]
On that note, it would be really nice if `Run` could return an `error` which gets just passed to `SetError` if it is set, for the simple error case, the code becomes much more aligned with the way regular error handling is written:

```go
func(req *cmds.Request, re cmds.ResponseEmitter, env cmds.Environment) {
  err := doSth()
  if err != nil {
    re.SetError(err, cmdkit.ErrNormal)
    return
  }
  re.Emit("cool")
}
// vs
func(req *cmds.Request, re cmds.ResponseEmitter, env cmds.Environment) error {
  err := doSth()
  if err != nil {
    return err
  }
  re.Emit("cool")
  return nil
}
```

**Comment by keks** [comment]
@whyrusleeping Can we close this in favour of #86?

**Comment by keks** [comment]
May I propose
```go
func(req *cmds.Request, re cmds.ResponseEmitter, env cmds.Environment) error {
  err := doSth()
  if err != nil {
    return err
  }
  return re.Emit("cool")
}
```
That way we don't lose the error and the code is still clean.

ping @whyrusleeping
