### ISSUE TITLE
MakeTypedEncoder breaks when using re.SetError

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/go-ipfs-cmds#65]
If I use `MakeTypedEncoder`, with a concrete type, say `*Foo` then the error case is not handled correctly anymore, as `SetError` calls `re.Emit` but not with type `*Foo` but rather `*cmdkit.Error`.

This results in a panic of `unexpected type: *cmdkit.Error`

**Comment by Stebalien** [comment]
Are you using this to encode responses sent over the network? The CLI response emitter *should* be special-casing errors and shouldn't be passing them to the encoder.

**Comment by dignifiedquire** [comment]
yeah this is over http

**Comment by Stebalien** [comment]
Hm. I wonder why I've never seen this in go-ipfs. But yeah, I see the bug.

**Comment by Stebalien** [comment]
Should be fixed with #112.

**Comment by Stebalien** [comment]
So, I implemented what I consider to be an "acceptable" fix: https://github.com/ipfs/go-ipfs-cmds/pull/128.
