### ISSUE TITLE
Handling of optional stdin arguments wrong

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-cmds#77]
Handling of stdin arguments doesn't take optional arguments into account.

**Comment by keks** [comment]
@Stebalien This should be fixed by https://github.com/ipfs/go-ipfs-cmds/commit/c6e9db3aef69ca80d0d52171ea9b87be5e15aadc, right?

**Comment by keks** [comment]
bump @Stebalien

**Comment by Stebalien** [comment]
I think so, yes.
