### ISSUE TITLE
ability to make api return 404

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs-cmds#90]
One thing we should be able to do is to return a 404 from a command. Originally, we were supposed to be able to do this via [cmdkit.ErrNotFound](https://github.com/ipfs/go-ipfs-cmdkit/blob/master/error.go#L16) but it seems that somewhere along the way, this broke.

It doesnt seem like that value is being used anywhere to actually return a 404.

Also, its worth noting that we will have to take care not to break this when re-applying: https://github.com/ipfs/go-ipfs-cmds/pull/87

**Comment by Stebalien** [comment]
So, what's the actual motivation for this? The commands lib is an RPC library over HTTP. It makes sense to return a 404 for a non-existent endpoint/function but I wouldn't return HTTP errors for failures within commands. At that point, I'd rather just (consistently) return an error in a trailer header.

**Comment by phritz** [comment]
The use case is an API that returns a specific requested object. If the object doesn't exist a 404 seems appropriately inline with http semantics. If the object is not found 500 does not seem appropriate, nor does 200. 

I do recognize that by returning 4xx we're conflating the status of the RPC with the status of the invocation. If there were more clear guidelines on how to signal different kinds of errors that might be helpful.

**Comment by Stebalien** [comment]
I believe one can pass back custom error codes in the `cmdkit.Error` object. Really, we shouln't be returning 500 codes either unless something goes wrong in the commands lib (just 200 + error).

Unfortunately, I have yet to find any consistency, rhyme, or reason anywhere in this library.

**Comment by Stebalien** [comment]
@whyrusleeping @phritz I'd like to close out this and #91 as "won't fix". Do we really need to be able to return HTTP 404's from *commands* or does the error code in the cmdkit Error suffice?

**Comment by phritz** [comment]
OK by me.

**Comment by Stebalien** [comment]
Got it. Thanks! We can reopen if anyone objects.
