### ISSUE TITLE
Don't read stdin when it's a terminal device

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-cmds#95]
Tools like grep test standard input to see if it's a tty (terminal device) and, if so, they don't bother reading from stdin. This is often what users expect and will allow us to print the help in that case (as most commands do).

Note: if we decide to do this, it will definitely be a breaking change.

**Comment by Kubuxu** [comment]
I very frequently use `ipfs add` with no arguments for stdin input but I think we can manually trigger this with `-`.

**Comment by Stebalien** [comment]
Hm. Fair enough. IPFS add is a case where one might want to do that. I was thinking more for `ipfs pin add`, etc. This will definitely require some thought.

**Comment by keks** [comment]
I'm not sure if this breaks CLI backwards compatiblity, which is important for shell scripting. However, I doubt there are many scripts that ask users to manually enter ipfs hashes, so probably it's not a big deal.

@Kubuxu `ipfs add -` already means something else: add the data read from stdin as an ipfs file.

How about we add a more descriptive explanation of what is happening when we read from stdin? If the current behaviour baffles users we could just tell them what's happening. Something like
```
$ ipfs add
ipfs called without arguments - call with -h for short or --help for long help.
reading arguments from stdin; send Ctrl-d to stop.
```

**Comment by keks** [comment]
> That was his point. If you want the old behaviour, you could run ipfs add - to explicitly read from stdin (even if it's a terminal).

I was under the impression that calling `ipfs add` would read file names from stdin that are going to be added, but apparently I was wrong.

>It does break backwards compat for users but shouldn't for shell scripts (unless something really weird is going on).

Would you check stdin or stdout for tty-ness? Because if we just check stdin, a shell script containing
```
echo "enter some data"
hash=$(ipfs add)
# ...
```
will suddenly break afaict.

**Comment by Stebalien** [comment]
@keks hm. Yeah, you're right. My plan was *just* to check stdin. (Note: that script would actually break either way as stdout wouldn't be a tty either).

Closing as this isn't worth breaking stuff over.
