### ISSUE TITLE
Rename SetError to CloseWithError

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmds#98]
At the moment, we basically only use SetError right before we close the connection, and using it for anything else has turned out to make things much more complicated than I thought.

The method `CloseWithError(error) error` is pretty common in Go, and returns the passed error to the caller of `Read` (or in our case `Next`) on the other side of the stream. Type information can be preserved for runtime-analysis, until we send the error through the http api, where it becomes a cmdkit.Error, if it isn't already.

@Stebalien do you have opinions on this?

**Comment by keks** [comment]
Actually not only rename, but also make it close the connection.

**Comment by Stebalien** [comment]
Sounds reasonable. Although, I assume the only use for this method will be from `PostRun`. `Run` can just return the error.

I wonder if it would be worth it to make PostRun synchronous as well and use the same "just return the error" system.

**Comment by keks** [comment]
> I assume the only use for this method will be from PostRun. Run can just return the error.

Well, Command.Call() also calls Run, so if that returns an error it needs to call CloseWithError to pass the error to the caller of the command.

> I wonder if it would be worth it to make PostRun synchronous as well and use the same "just return the error" system.

I'm not sure what you mean here. Do you want to first call run and capture the output, and then let PostRun postprocess the result? Because we did that before the rewrite and that was terrible.
One example: In `pubsub sub` we need to flush the connection once we successfully set up the subscription to send out the http header - otherwise the client would block until the first message is received. That was not possible with the previous system, we had to send an empty dummy value that was ignored by the recipient. I'd rather not go back to that system.

One more note: Using CloseWithError would clarify our sematics around passing errors and make explicit that fatal errors are returned as errors and status errors are returned as values.

**Comment by Stebalien** [comment]
> Well, Command.Call() also calls Run, so if that returns an error it needs to call CloseWithError to pass the error to the caller of the command.

Ah, I forgot about that.

> I'm not sure what you mean here. Do you want to first call run and capture the output, and then let PostRun postprocess the result?

I mean define PostRun as:

```go
type PostRunFunc = func(req *Request, in Response, out ResponseEmitter) error
```

While users *could* call `CloseWithError`, the correct way would be to return an error. Am I missing something here?

**Comment by Stebalien** [comment]
> Well, it depends. Some errors should go to the connection (requested item not found, etc.) while others should be returned (could not write to connection).

My entire motivation to returning an error is to *not* have to call any form of `CloseWithError` function. IMO, *all* errors returned from either Run or PostRun should be returned to the client if possible.

**Comment by keks** [comment]
Yeah maybe you're right. I started a branch where I change the PostRun signature: `refactor/postrun`. I'll start going for `CloseWithError` later today.

**Comment by Stebalien** [comment]
DOne.
